#服务端口
server:
  port: 37902

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/parkerpal?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# swagger配置
swagger:
  #是否开启swagger文档，true|开启  false｜关闭
  enable: true
  # 标题
  title: "智泊无忧接口文档"
  # 说明
  description: "智泊无忧接口文档描述"
  # 版本号
  version: "1.0.0"

# 微信支付
wxpay:
  enabled: false

# 文件上传配置
file:
  # 是否开启第三方作为文件上传存储，true|开启  false｜关闭
  thirdParty: false
  # log上传地址
  root: /opensource/smartParking/backend/log/
  # 停车领劵二维码生成地址
  qrCode: /Users/betacat/Code/Java/parkerpal-service/static/qrcode/
  # 商户私钥文件上传地址
  privateKeyPath: /opensource/smartParking/backend/wxpay/

# MQTT配置
mqtt:
  # 是否开启MQTT，true|开启  false｜关闭
  enabled: true
  # 服务地址+端口
  brokerUrl: tcp://127.0.0.1:1883
  # 用户名
  username: ParkerPal
  # 密码
  password: 123456
  # 客户端
  client:
    id: ParkerPal-Service
  # 默认主题
  topic:
    default: /parkerpal/#
    subscribe: /parkerpal
    sensor:
      subPrefix : Sensor-Sub- # 设备监听前缀
      pubPrefix : Sensor-Pub- # 设备发布前缀
  # QoS
  qos: 1

  # 用于配置传感器的MQTT
  sensorBroker:
    ip: 192.168.100.205 # 禁止写本地回环地址
    port: 1883
    username: ParkerPal
    password: 123456

# 终端设备
iot:
  controlGate: false

# redis配置
#redis:
#  host: 127.0.0.1
#  port: 6379