#服务端口
server:
  port: 37902

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.72.75.41:3306/smart_parking?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: mysql_b5YQEa

# swagger配置
swagger:
  #是否开启swagger文档，true|开启  false｜关闭
  enable: true
  # 标题
  title: "智泊无忧接口文档"
  # 说明
  description: "智泊无忧接口文档描述"
  # 版本号
  version: "1.0.0"

# 文件上传配置
file:
  # 是否开启第三方作为文件上传存储，true|开启  false｜关闭
  thirdParty: false
  # log上传地址
  root: /opensource/smartParking/backend/log/
  # 停车领劵二维码生成地址
  qrCode: /opensource/smartParking/backend/qrcode/
  # 商户私钥文件上传地址
  privateKeyPath: /opensource/smartParking/backend/wxpay/

# 微信支付
wxpay:
  enabled:false
